import { useNavigation } from '@react-navigation/native'
import { SafeAreaView } from 'react-native'
import { Text, YStack } from 'tamagui'

import { MenuItemCard } from '@/components'

export default function AddElectricityExportRateScreen(): React.JSX.Element {
  const { navigate } = useNavigation()
  return (
    <SafeAreaView>
      <YStack
        padding="$4"
        space="$3"
        marginBottom="$10"
      >
        <Text
          fontFamily="$body"
          fontWeight="500"
          marginLeft="$1"
        >
          Select your electricity export plan
        </Text>
        <MenuItemCard
          title="NEM(Net Energy Metering)"
          description="Check this if you have a net meter configuration at your home. Your electricity import rate will be copied as your electricity export rate"
          onPress={() => navigate('SettingsAddElectricityExportRateNEM')}
        />
        <MenuItemCard
          title="Net FIT(Net Feed-In Tariff)"
          description="Check this if you only get paid for solar energy that goes back into the grid from your house"
          onPress={() => navigate('SettingsAddElectricityExportRateNet')}
        />
        <MenuItemCard
          title="Gross FIT(Gross Feed-In Tariff)"
          description="Check this if you get paid for every unit of electricity generated by your solar panels."
          onPress={() => navigate('SettingsAddElectricityExportRateGross')}
        />
        <MenuItemCard
          title="Other"
          description="Check this if you are on any other plan"
          onPress={() => navigate('SettingsAddElectricityExportRateOther')}
        />
      </YStack>
    </SafeAreaView>
  )
}
